add some blabla to make shell scripts more friendly

diff --git a/springboot/maven-3.2.5/jdk-1.8/s2i/bin/assemble b/springboot/maven-3.2.5/jdk-1.8/s2i/bin/assemble
--- a/springboot/maven-3.2.5/jdk-1.8/s2i/bin/assemble
+++ b/springboot/maven-3.2.5/jdk-1.8/s2i/bin/assemble
@@ -42,9 +42,9 @@ if [ -f "$LOCAL_SOURCE_DIR/$POM_PATH/pom.xml" ]; then
   if [[ "$INCREMENTAL" = "true" ]]; then 
     # restore any maven dependencies which will be present if this is an
     # incremental build
-    echo "INCREMENTAL is set to $INCREMENTAL, we are restoring cached workspace containing .m2..."
+    echo -n "INCREMENTAL is set to $INCREMENTAL, we are restoring cached workspace containing .m2..."
     restore_saved_artifacts
-    echo "...restored"
+    echo " restored"
 
   fi
 
@@ -84,17 +84,23 @@ if [ -f "$LOCAL_SOURCE_DIR/$POM_PATH/pom.xml" ]; then
     exit $ERR
   fi
 
-  echo "Cleaning $DEPLOY_DIR..."
+  echo -n "Cleaning $DEPLOY_DIR..."
   rm -rf $DEPLOY_DIR/*
+  echo " cleaned up"
 
-  echo "Moving built war file `find -name $JAR_NAME` into $DEPLOY_DIR for later deployment..."
-
-  mv `find -name $JAR_NAME` $DEPLOY_DIR
+  if [ ! -z `find -name $JAR_NAME` ]
+  then
+    echo "Moving built jar file `find -name $JAR_NAME` into $DEPLOY_DIR for later deployment..."
+    mv `find -name $JAR_NAME` $DEPLOY_DIR
+  else
+    echo "Aborting due to error : File not found, moving $JAR_NAME file, maybe it doesn't exist"
+    exit 1
+  fi
 
   if [[ "$INCREMENTAL" = "false" ]]; then
-    echo "INCREMENTAL is set to $INCREMENTAL, we are now cleaning image \"rm -rf . .m2\"..."
-    rm -rf . .m2
-    echo "...cleaned up"
+    echo -n "INCREMENTAL is set to $INCREMENTAL, we are now cleaning image \"rm -rf ./* .m2\"..."
+    rm -rf ./* .m2
+    echo " cleaned up"
   fi
   popd &> /dev/null
 else
